database:
  client: "mysql"
  max_idle: 10
  max_life_time: "1h"
  max_open_conn: 100
  user: "root"
  password: "bimap1234"
  host: "localhost"
  name: "warroom"
  port: "3306"
  params: "charset=utf8mb4&parseTime=True&loc=Asia%2fTaipei"
  log_enable: 0

server: 
  mode: debug
  port: :8005

other:
  backend: "localhost:3002"
  migration: true

cors:
  allow:
    headers: "Content-type Access-Control-Allow-Origin Authorization Refresh-token"
  default_allow_url: "http://localhost:8080"


reportengine:
  picturePath: /Users/chen/Documents/gitlab/git-out/product/report-backend/pdf/pics
  htmlPath: "/Users/chen/Documents/gitlab/git-out/product/report-backend/pdf/html"
  pdfPath: "/Users/chen/Documents/gitlab/git-out/product/report-backend/pdf/pdf_file"
  logPath: "/Users/chen/Documents/gitlab/git-out/product/report-backend/log/schedule.log"


email:
  user: "rabot6201@gmail.com"
  password: "mohptlqcqeiisshx"
  host: "smtp.gmail.com"
  port: "587"
  subject: ""
