database:
  client: "mysql"
  max_idle: 10
  max_life_time: "1h"
  max_open_conn: 100
  user: "root"
  password: "1qaz2wsx"
  host: "localhost"
  name: "warroom"
  port: "3306"
  params: "charset=utf8mb4&parseTime=True&loc=Asia%2fTaipei"
  log_enable: 0

server: 
  mode: debug
  port: :8005

other:
  backend: "localhost:3002"
  migration: true

cors:
  allow:
    headers: "Content-type Access-Control-Allow-Origin Authorization Refresh-token"
  default_allow_url: "http://localhost:8080"
