package entities

type Dataview struct {
	Common
	ID         int        `gorm:"primaryKey;index" json:"id" form:"id"`
	Name       string     `gorm:"type:varchar(50)" json:"name" form:"name"`
	TimeUnit   string     `gorm:"type:varchar(50)" json:"time_unit" form:"time_unit"`
	TimePeriod int        `gorm:"type:int" json:"time_period" form:"time_period"`
	Alias      string     `gorm:"type:varchar(45)" json:"alias" form:"alias"`
	Elements   []Element  `gorm:"foreignKey:ReportID;constraint:OnUpdate:RESTRICT,OnDelete:RESTRICT;"`
	Schedules  []Schedule `gorm:"many2many:reports_schedules;"`
}


type AutoGenerated struct {
	DataView []struct {
		ID         string   `json:"id"`
		Namespaces []string `json:"namespaces"`
		Title      string   `json:"title"`
		TypeMeta   struct {
		} `json:"typeMeta,omitempty"`
		Name string `json:"name,omitempty"`
	} `json:"data_view"`
}


