basePath: /api/v1
definitions:
  entities.Dropdown:
    properties:
      text:
        type: string
      value:
        type: string
    type: object
  entities.Element:
    properties:
      column_type:
        type: string
      created_at:
        type: integer
      deleted_at:
        type: integer
      id:
        type: integer
      instance:
        $ref: '#/definitions/entities.Instance'
      instance_id:
        type: integer
      name:
        type: string
      report_id:
        type: integer
      row_num:
        type: integer
      space_name:
        type: string
      type:
        type: string
      uid:
        type: string
      updated_at:
        type: integer
    type: object
  entities.Instance:
    properties:
      auth:
        type: integer
      created_at:
        type: integer
      deleted_at:
        type: integer
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      type:
        type: string
      updated_at:
        type: integer
      url:
        type: string
      user:
        type: string
    type: object
  entities.Report:
    properties:
      created_at:
        type: integer
      deleted_at:
        type: integer
      elements:
        items:
          $ref: '#/definitions/entities.Element'
        type: array
      id:
        type: integer
      name:
        type: string
      schedules:
        items:
          $ref: '#/definitions/entities.Schedule'
        type: array
      time_period:
        type: integer
      time_unit:
        type: string
      updated_at:
        type: integer
    type: object
  entities.Schedule:
    properties:
      bcc:
        items:
          type: string
        type: array
      cc:
        items:
          type: string
        type: array
      created_at:
        type: integer
      cron_id:
        type: integer
      cron_time:
        type: string
      deleted_at:
        type: integer
      id:
        type: integer
      name:
        type: string
      reports:
        items:
          $ref: '#/definitions/entities.Report'
        type: array
      to:
        description: |-
          To       []string `gorm:"type:varchar(50)" json:"to" form:"to"`
          CC       []string `gorm:"type:varchar(50)" json:"cc" form:"cc"`
          BCC      []string `gorm:"type:varchar(50)" json:"bcc" form:"bcc"`
        items:
          type: string
        type: array
      updated_at:
        type: integer
    type: object
  models.Element:
    properties:
      column_type:
        type: string
      created_at:
        type: integer
      deleted_at:
        type: integer
      id:
        type: integer
      instance:
        $ref: '#/definitions/models.Instance'
      instance_id:
        type: integer
      name:
        type: string
      report_id:
        type: integer
      row_num:
        type: integer
      space_name:
        type: string
      type:
        type: string
      uid:
        type: string
      updated_at:
        type: integer
    type: object
  models.Instance:
    properties:
      auth:
        type: integer
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      type:
        type: string
      url:
        type: string
      user:
        type: string
    type: object
  models.Report:
    properties:
      created_at:
        type: integer
      deleted_at:
        type: integer
      elements:
        items:
          $ref: '#/definitions/models.Element'
        type: array
      id:
        type: integer
      name:
        type: string
      time_period:
        type: integer
      time_unit:
        type: string
      updated_at:
        type: integer
    type: object
  models.Response:
    properties:
      body: {}
      msg:
        type: string
      success:
        type: boolean
    type: object
host: 10.99.1.127:8005
info:
  contact:
    email: support@swagger.io
    name: Winston
  description: Golang API 專案描述
  termsOfService: http://swagger.io/terms/
  title: Report Engine Golang API
  version: "1.0"
paths:
  /Dropdown:
    get:
      consumes:
      - application/json
      parameters:
      - description: space,dashboard,visualization
        in: query
        name: source_type
        required: true
        type: string
      - description: space_name
        in: query
        name: space_name
        type: string
      - description: instance_id
        in: query
        name: instance_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Dropdown'
      security:
      - ApiKeyAuth: []
      summary: Get Space of Instance by Instance ID
      tags:
      - Dropdown
  /Element/Create:
    post:
      consumes:
      - application/json
      parameters:
      - description: element
        in: body
        name: Element
        required: true
        schema:
          $ref: '#/definitions/entities.Element'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Create Element
      tags:
      - Element
  /Element/Delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete Element
      tags:
      - Element
  /Element/GetAll:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get Element
      tags:
      - Element
  /Element/GetElementByReportID/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: report id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Element'
      security:
      - ApiKeyAuth: []
      summary: Get Element by Report ID
      tags:
      - Element
  /Element/Update:
    put:
      consumes:
      - application/json
      parameters:
      - description: instance
        in: body
        name: Instacne
        required: true
        schema:
          $ref: '#/definitions/entities.Element'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update Element
      tags:
      - Element
  /History/GetAll:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get history
      tags:
      - History
  /History/GetOldHistory:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get Old history
      tags:
      - History
  /Html/Create/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: Html
      tags:
      - Html
  /Instance/Create:
    post:
      consumes:
      - application/json
      parameters:
      - description: instance
        in: body
        name: Instance
        required: true
        schema:
          $ref: '#/definitions/models.Instance'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Create Instance
      tags:
      - Instance
  /Instance/Delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete Instance
      tags:
      - Instance
  /Instance/GetAll:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get Instance
      tags:
      - Instance
  /Instance/GetDashboards/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: instance id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Element'
      security:
      - ApiKeyAuth: []
      summary: Get Dashboard of server by Instance ID
      tags:
      - Instance
  /Instance/GetVisualizations/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: instance id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Element'
      security:
      - ApiKeyAuth: []
      summary: Get Visualization of server by Instance ID
      tags:
      - Instance
  /Instance/Update:
    put:
      consumes:
      - application/json
      parameters:
      - description: instance
        in: body
        name: Instacne
        required: true
        schema:
          $ref: '#/definitions/models.Instance'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update Instance
      tags:
      - Instance
  /Mail/Send/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: Mail
      tags:
      - Mail
  /PDF/Create/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: PDF
      tags:
      - PDF
  /Report/Create:
    post:
      consumes:
      - application/json
      parameters:
      - description: report
        in: body
        name: Report
        required: true
        schema:
          $ref: '#/definitions/models.Report'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Create Report
      tags:
      - Report
  /Report/Delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete Report
      tags:
      - Report
  /Report/GetAll:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get Report
      tags:
      - Report
  /Report/GetReport/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Report'
      security:
      - ApiKeyAuth: []
      summary: Get report by Report ID
      tags:
      - Report
  /Report/GetReportByScheduleID/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: schedule id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Schedule'
      security:
      - ApiKeyAuth: []
      summary: Get Report by Schedule ID
      tags:
      - Report
  /Report/Update:
    put:
      consumes:
      - application/json
      parameters:
      - description: report
        in: body
        name: Instacne
        required: true
        schema:
          $ref: '#/definitions/models.Report'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update Report
      tags:
      - Report
  /SSO/GetURL:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get SSOUrl
      tags:
      - SSO
  /Schedule/Create:
    post:
      consumes:
      - application/json
      parameters:
      - description: schedule
        in: body
        name: Schedule
        required: true
        schema:
          $ref: '#/definitions/entities.Schedule'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Create Schedule
      tags:
      - Schedule
  /Schedule/Delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete Schedule
      tags:
      - Schedule
  /Schedule/GetAll:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get Schedule
      tags:
      - Schedule
  /Schedule/GetSchedule/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: Get Schedule by Schedule ID
      tags:
      - Schedule
  /Schedule/Update:
    put:
      consumes:
      - application/json
      parameters:
      - description: schedule
        in: body
        name: Schedule
        required: true
        schema:
          $ref: '#/definitions/entities.Schedule'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update Schedule
      tags:
      - Schedule
  /Screenshot/Create/{id}:
    post:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      security:
      - ApiKeyAuth: []
      summary: ScreenShot
      tags:
      - ScreenShot
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
