basePath: /api/v1
definitions:
  models.Instance:
    properties:
      auth:
        type: boolean
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      type:
        type: string
      url:
        type: string
      user:
        type: string
    type: object
  models.Response:
    properties:
      body: {}
      msg:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8005
info:
  contact:
    email: support@swagger.io
    name: Winston
  description: Golang API 專案描述
  termsOfService: http://swagger.io/terms/
  title: Report Engine Golang API
  version: "1.0"
paths:
  /Instance/Create:
    post:
      consumes:
      - application/json
      parameters:
      - description: instance
        in: body
        name: Instance
        required: true
        schema:
          $ref: '#/definitions/models.Instance'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Create Instance
      tags:
      - Instance
  /Instance/Delete/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete Instance
      tags:
      - Instance
  /Instance/GetAll:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get Instance
      tags:
      - Instance
  /Instance/Update:
    put:
      consumes:
      - application/json
      parameters:
      - description: instance
        in: body
        name: Instacne
        required: true
        schema:
          $ref: '#/definitions/models.Instance'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update Instance
      tags:
      - Instance
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
